version: '3.8'

services:
  postgres:
    restart: 'always'
    image: postgres:14.4-alpine
    networks:
      - db
    volumes:
      - ./students.sql:/docker-entrypoint-initdb.d/schema.sql
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      timeout: 2s
      interval: 5s
      retries: 10
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - db

networks:
  db:
